#!/bin/bash

# ensure this env var has no impact
unset DOCKER_SERVICES

function usage() {
cat << EOF

fug - faster and uglier than fig.

Builds, starts and stops docker containers. Can also be used to view the docker log
files. Uses ./fug.yml for configuration, which is similar syntactically to Fig's fig.yml.

USAGE:

    $(basename $0) [-c FILE] [-d|-l|-L|-b|-B|-s|-e NAMES] [-v] [-h]

OPTIONS:

    -c FILE         config file, default: ./fug.yml
    -d [NAMES]      run the services in daemon mode
    -l [NAMES]      show logs
    -L [NAMES]      show logs and exit
    -b [NAMES]      build services
    -B [NAMES]      build services, without using cache
    -s [NAMES]      stop containers
    -e NAME         exec into a container
    -v              verbose debugging
    -h              display this help

Fug looks for a fug.yml file that defines the manner in which docker run is invoked for
each service. The fug.yml file supports environment variables in \${SOMEVAR} format.

EOF
}

function get_ops() {
  # We are reinventing getopts because I want support for optional parameters,
  # and I want support for space separated non-shell-escaped parameters, eg:
  # fug -b target1 target2 and fug -b. May I offer a hearty F.U. to getopts,
  # getopt et al, get off my lawn!
  #
  # This function populates the global associative array $CLI of the users
  # command line arguments, eg: CLI["-d"]="arg1 arg2"

  local -A FP_START FP_END
  local FLAG=""
  local k=0
  local i f

  for i in $@; do
    let k=k+1
    if [ "${i:0:1}" == "-" ]; then
      [ -n "${FLAG}" ] && FP_END[$FLAG]=$(($k-${FP_START[$FLAG]}))
      FLAG=${i}
      FP_START[$FLAG]=$(($k+1))
    fi
    [ -n "${FLAG}" ] && [ -z ${FP_END[$FLAG]} ] && FP_END[$FLAG]=${#@}
  done

  for f in ${!FP_START[@]}; do
    if [ -n "${FP_START[$f]}" ]; then
      CLI[$f]=${@:${FP_START[$f]}:${FP_END[$f]}}
    fi
  done
}

# grab valid command line args from usage() function
function validate_ops() {
  local -A CLI_VALID CLI_MANDATORY
  local line i
  while read -r line; do
    local f=$(echo "$line" | grep -Eo '^\s*-[A-Za-z]')
    local t=$(echo "$line" | grep -Eo '^\s*-[A-Za-z] [A-Za-z]')
    [ "$f" ] && CLI_VALID[$f]=1
    [ "$t" ] && CLI_MANDATORY[$f]=1
  done <<< "$(usage)"

  # loop through the switches the user has typed in
  for i in ${!CLI[@]}; do
    [ -z "${CLI_VALID[$i]}" ] && echo "not supported: $i" && exit 1
    [ "${CLI_MANDATORY[$i]}" ] && [ -z "${CLI[$i]}" ] && echo "empty value for: $i" && exit 1
  done
}

# when a command line flag is supplied without args
function default_ops() {
  local -A CLI_DEFAULTS
  local f
  CLI_DEFAULTS["-d"]=$DOCKER_SERVICES
  CLI_DEFAULTS["-l"]=$DOCKER_SERVICES
  CLI_DEFAULTS["-L"]=$DOCKER_SERVICES
  CLI_DEFAULTS["-b"]=$DOCKER_SERVICES_REVERSED
  CLI_DEFAULTS["-B"]=$DOCKER_SERVICES_REVERSED
  CLI_DEFAULTS["-s"]=$DOCKER_SERVICES_REVERSED

  for f in ${!CLI[@]}; do
    if [ -z "${CLI[$f]}" ] && [ "${CLI_DEFAULTS[$f]}" ]; then
      CLI[$f]=${CLI_DEFAULTS[$f]}
    fi
  done
}

function get_docker_run_args() {
  # parse the fug.yml configuration file
  for i in $(${FUGDIR}/shyaml keys < ${OPCONF}); do
    DOCKER_LINKS[$i]+=$(  ${FUGDIR}/shyaml get-value ${i}.links       < ${OPCONF} | sed 's/- / /g')
    DOCKER_ENV[$i]+=$(    ${FUGDIR}/shyaml get-value ${i}.environment < ${OPCONF} | sed 's/- / /g')
    DOCKER_ENVFILE[$i]+=$(${FUGDIR}/shyaml get-value ${i}.env-file    < ${OPCONF} | sed 's/- / /g')
    DOCKER_EXTRA[$i]+=$(  ${FUGDIR}/shyaml get-value ${i}.extra       < ${OPCONF} | sed 's/- / /g')
    DOCKER_ROOT[$i]+=$(   ${FUGDIR}/shyaml get-value ${i}.privileged  < ${OPCONF} | sed 's/- / /g')
    DOCKER_PORTS[$i]+=$(  ${FUGDIR}/shyaml get-value ${i}.ports       < ${OPCONF} | sed 's/- / /g')
    DOCKER_VOLUMES[$i]+=$(${FUGDIR}/shyaml get-value ${i}.volumes     < ${OPCONF} | sed 's/- / /g')
    DOCKER_VOLFROM[$i]+=$(${FUGDIR}/shyaml get-value ${i}.vol-from    < ${OPCONF} | sed 's/- / /g')
    DOCKER_HOSTS[$i]+=$(  ${FUGDIR}/shyaml get-value ${i}.hosts       < ${OPCONF} | sed 's/- / /g')
  done

  # build up command line argument to docker run
  for i in $DOCKER_SERVICES; do
    for v in ${DOCKER_LINKS[$i]};   do ARGS[$i]+=" --link=${NAME}_${v}:${v}";    done
    for v in ${DOCKER_ENV[$i]};     do ARGS[$i]+=" --env=$v";                    done
    for v in ${DOCKER_ENVFILE[$i]}; do ARGS[$i]+=" --env-file=${v}";             done
    for v in ${DOCKER_VOLUMES[$i]}; do ARGS[$i]+=" --volume=$v";                 done
    for v in ${DOCKER_VOLFROM[$i]}; do ARGS[$i]+=" --volumes-from=${NAME}_${v}"; done
    for v in ${DOCKER_ROOT[$i]};    do ARGS[$i]+=" --privileged";                done
    for v in ${DOCKER_HOSTS[$i]};   do ARGS[$i]+=" --add-host=$v";               done
    for v in ${DOCKER_EXTRA[$i]};   do ARGS[$i]+=" $v";                          done
    for v in ${DOCKER_PORTS[$i]};   do ARGS[$i]+=" --publish=$v";                done
  done
}

function get_docker_build_args() {
  # parse the fug.yml configuration file
  for i in $(${FUGDIR}/shyaml keys < ${OPCONF}); do
    DOCKER_PATH[$i]+=$(   ${FUGDIR}/shyaml get-value ${i}.build       < ${OPCONF} | sed 's/- / /g')
  done
}

function stop_containers() {
  local services=$@
  local i
  for i in $services; do
    nuke_container $i
  done
}

function nuke_container() {
  local i=$1
  local x
  local ids="$(docker ps -a | grep -E "\b${NAME}_${i}\b" | awk '{print $1}')"
  for x in $ids; do
    if [ -n "${x}" ]; then
      echo " * Stopping ${NAME}_${i} ($x)"
      docker stop -t 0 $x > /dev/null
      docker rm -f $x > /dev/null
    fi
  done
}

function halt_log() {
  services=$@
  local i x
  for i in $services; do
    local ids="$(docker ps | grep -E "\b${NAME}_${i}\b" | awk '{print $1}')"
    for x in $ids; do
      if [ -n "${x}" ]; then
        local pid=$(pgrep -f "docker logs -f ${x}")
        [ -n "${pid}" ] && kill $pid
      fi
    done
  done
}

function listen() {
  local x
  while true; do
    read x
    sleep 1
  done
}

function build_container() {
  # build new images
  local i=$1
  local p nocache
  if [ -n "${DOCKER_PATH[$i]}" ]; then
    p="${DOCKER_PATH[$i]}"
  else
    p="./${i}/"
  fi
  [ -n "${OPBUILD_NOCACHE}" ] && nocache="--no-cache"
  local cmd="docker build ${nocache} -t ${NAME}_${i} $p"

  # if verbose, then we run in non-concurrent build mode
  if [ -n "${OPVERBOSE}" ]; then
    echo " * Building $i (${NAME}_${i}) "
    $cmd
    if [ "$?" != "0" ]; then
     echo "*** Build container failed: $i"
     exit 1
    fi
  # else, build containers concurrently
  else
    $cmd > /dev/null 2>&1 &
    PIDS[$i]="$!"
  fi
}

function watch_containers_build() {
  # EXITS will contain docker build exit statuses
  local -A EXITS
  local ticker i
  trap "{ echo ''; exit 1; }" SIGINT
  while [ true ]; do
    # if no more processes, then break loop
    [ "${#PIDS[@]}" == "0" ] && break

    ((ticker++))

    for i in ${!PIDS[@]}; do
      if [ "${PIDS[$i]}" ] && [ "$(ps -p${PIDS[$i]} --no-headers)" ]; then
        EXITS[$i]="-1"
      elif [ "${PIDS[$i]}" ]; then
        wait ${PIDS[$i]}
        EXITS[$i]=$? # exit status of container build process
        unset PIDS[$i]
      fi
    done

    # echo out an updating status line
    if [ -z "${OPVERBOSE}" ]; then
      echo -n "Build(${ticker}s): "
      for i in $OPBUILD; do
        if [ "${EXITS[$i]}" == "-1" ] ; then
          echo -n "$i "
        elif [ "${EXITS[$i]}" != "0" ] ; then
          echo -ne "${red}${i}${end_colour} "
        else
          echo -ne "${green}${i}${end_colour} "
        fi
      done
      echo -ne '\r' # backspace the whole line
    fi
    sleep 1
  done

  [ -z "${OPVERBOSE}" ] && echo ""

  for i in ${!EXITS[@]}; do
    if [ "${EXITS[$i]}" != "0" ]; then
     echo "*** Build container failed: $i"
     exit 1
   fi
  done
}

function inherit_container_environment() {
  local i=$1
  local id=$(docker ps | grep -E "\b${NAME}_${i}\b" | awk '{ print $1 }')
  if [ "${id}" ]; then
    for v in ${DOCKER_ENVFILE[$i]}; do
      unset exportvars
      [ -f "./${i}/${v}" ] && exportvars=$(docker exec $id env | sed 's/\(.*\)=\(.*$\)/export \1="\2"/g' | grep -f ./${i}/${v})
      [ -n "$exportvars" ] && eval "$exportvars"
    done
  fi
}

function load_docker_services() {
  # Check fug.yml for list of services
  local i
  for i in $(${FUGDIR}/shyaml keys < "${OPCONF}"); do
    DOCKER_SERVICES+="${i} "
  done
  [ -z "${DOCKER_SERVICES}" ] && echo "No services found in config file." && exit 1
  for i in $DOCKER_SERVICES; do DOCKER_SERVICES_REVERSED="$i $DOCKER_SERVICES_REVERSED"; done
}


# These are the currently supported docker settings
declare -A DOCKER_LINKS DOCKER_ENV DOCKER_EXTRA DOCKER_ROOT DOCKER_PORTS
declare -A DOCKER_VOLUMES DOCKER_VOLFROM DOCKER_HOSTS DOCKER_PATH DOCKER_ENVFILE

# where `docker run` cli options are constructed, PIDS is for build process ids
declare -A ARGS PIDS CLI

# Location of script
FUGDIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Some colours
red='\033[0;31m'
green='\033[0;32m'
end_colour='\033[0m' # No Color

# Setup the valid cli options and their defaults
get_ops "$@"
validate_ops


# get the configuration file
[ -n "${CLI["-c"]+q}" ] && OPCONF=${CLI["-c"]}     good=1
[ -z "${OPCONF}" ]      && OPCONF="./fug.yml"
[ ! -f "${OPCONF}" ]    && echo "no configuration file found: ${OPCONF}" && exit 1

# populate DOCKER_SERVICES from fug.yml
load_docker_services

# set default args for options left blank
default_ops

# make the ops slightly easier to read. The +q hack permits
# checking for array keys that have empty values
[ -n "${CLI["-d"]+q}" ] && OPDAEMON=${CLI["-d"]}   good=1
[ -n "${CLI["-l"]+q}" ] && OPLOGS=${CLI["-l"]}     good=1
[ -n "${CLI["-L"]+q}" ] && OPLOGSEXIT=${CLI["-L"]} good=1
[ -n "${CLI["-b"]+q}" ] && OPBUILD=${CLI["-b"]}    good=1
[ -n "${CLI["-B"]+q}" ] && OPBUILD=${CLI["-B"]}    good=1 OPBUILD_NOCACHE=1
[ -n "${CLI["-s"]+q}" ] && OPSTOP=${CLI["-s"]}     good=1
[ -n "${CLI["-e"]+q}" ] && OPEXEC=${CLI["-e"]}     good=1
[ -n "${CLI["-v"]+q}" ] && OPVERBOSE=1             good=1
[ -n "${CLI["-h"]+q}" ] && OPHELP=1                good=1

# helper monkeys
[ -n "${OPVERBOSE}" ] && env && set -o xtrace
[ -n "${OPHELP}" ]    && usage && exit 0
[ -z "${good}" ]      && usage && exit 1

# get an alphanumeric name for the containers base on the current working directory
NAME="fug_$(basename $(pwd) | sed 's/[^A-Za-z0-9]//g')"

# If they want to exec into a container
if [ "${OPEXEC}" ]; then
  id=$(docker ps | grep -E "\b${NAME}_${OPEXEC}\b" | awk '{ print $1 }')
  [ "${id}" ] && docker exec -it $id bash
  exit $?
fi

# load up build args from fug.yml
get_docker_build_args

# stop mode
if [ -n "${OPSTOP}" ]; then
  stop_containers ${OPSTOP}
  exit $?
fi

# show logs, like a tail -f
if [ -n "${OPLOGS}" ]; then
  trap "{ halt_log ${OPLOGS} ; exit 0; }" SIGINT
  for i in ${OPLOGS}; do
    id="$(docker ps | grep -E "\b${NAME}_${i}\b" | awk '{print $1}')"
    if [ -n "${id}" ]; then
      docker logs -f $id &
      go=1
    else
      echo "Not started: ${NAME}_${i}"
    fi
  done
  [ -n "${go}" ] && listen
  exit $?
fi

# show logs and exit
if [ -n "${OPLOGSEXIT}" ]; then
  for i in ${OPLOGSEXIT}; do
    id="$(docker ps | grep -E "\b${NAME}_${i}\b" | awk '{print $1}')"
    if [ -n "${id}" ]; then
      docker logs $id
    else
      echo "Not started: ${NAME}_${i}"
    fi
  done
  exit $?
fi

# If running -b then build and exit
if [ "${OPBUILD}" ]; then
  for i in ${OPBUILD}; do
    build_container ${i}
  done
  watch_containers_build
  exit $?
fi

# default is to run the container - but check if it exists first, if not, build it
images="$(docker images | awk '{ print $1 }')"
for i in ${OPDAEMON}; do
  exists=$(grep "${NAME}_${i}" <<< "$images")
  if [ -z "${exists}" ]; then
    build_container ${i}
  fi
done
[ -z "${exists}" ] && watch_containers_build

get_docker_run_args
for i in ${OPDAEMON}; do
  unset PORT
  inherit_container_environment $i
  nuke_container $i
  echo " * Starting ${NAME}_${i}"
  customport="PORT_${i}"
  [ "${!customport}" ] && export PORT=${!customport}

  # run and background the docker process
  nohup docker run --restart=always ${ARGS[$i]} --name=${NAME}_${i} ${NAME}_${i} > /dev/null 2>&1 &

  # artificial delay to permit docker links to work correctly
  [ "${DOCKER_LINKS[$i]}" ] && sleep 0.5
done

